apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../deploy/apps
patches:
  - path: jfrog-values.yaml
    target:
      kind: HelmRelease
      name: artifactory
  - path: promethues-metrics-production.yaml
    target:
      kind: HelmRelease
      name: monitoring

configMapGenerator:
  - name: jfrog-values
    namespace: production
    files:
      - values.yaml=jfrog-production-values.yaml

generatorOptions:
  disableNameSuffixHash: true
