grafana:
  enabled: false

# Disable AlertManager - centralized in hub cluster  
alertmanager:
  enabled: false

# Configure Prometheus with minimal resources and remote write
prometheus:
  service:
    type: NodePort
    nodePort: 30901
    port: 9090
  prometheusSpec:
    # Minimal retention since metrics are sent to hub
    retention: "2h"
    retentionSize: "1GB"
    enableOTLPReceiver: false
    
    # Even more reduced resource allocation for production
    resources:
      requests:
        memory: "300Mi"
        cpu: "75m"
      limits:
        memory: "600Mi" 
        cpu: "150m"
    
    # Storage configuration - smaller for production
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi    
    # External labels
    externalLabels:
      cluster: "production"
      environment: "production"

# Keep kube-state-metrics for cluster-specific metrics
kube-state-metrics:
  enabled: true
  resources:
    requests:
      memory: "96Mi"
      cpu: "25m"
    limits:
      memory: "192Mi"
      cpu: "50m"

# Keep node-exporter for node metrics
nodeExporter:
  enabled: true
  resources:
    requests:
      memory: "48Mi"
      cpu: "25m"
    limits:
      memory: "96Mi"
      cpu: "50m"

# Simplified Prometheus Operator configuration
prometheusOperator:
  # Disable admission webhooks for simplicity
  admissionWebhooks:
    enabled: false
  
  # Disable TLS for internal communication
  tls:
    enabled: false
    
  # Reduced resource allocation
  resources:
    requests:
      memory: "96Mi"
      cpu: "25m"
    limits:
      memory: "192Mi"
      cpu: "50m"