apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jfrog.yaml
  - promethues-metrics.yaml

configMapGenerator:
  - name: prometheus-values
    namespace: monitoring
    files:
      - values.yaml=promethues-hub-values.yaml
