apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: monitoring
      interval: 12h
      version: "77.x"
  test:
    enable: false
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-values
      valuesKey: values.yaml
